version: '3.1'
volumes:
    prometheus_data_1: {}
    prometheus_data_2: {}
    prometheus_data_3: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:

  prometheus_1:
    image: prom/prometheus:v2.7.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data_1:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus_1.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  prometheus_2:
    image: prom/prometheus:v2.7.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data_2:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus_2.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9091:9090
    networks:
      - back-tier
    restart: always

  prometheus_3:
    image: prom/prometheus:v2.7.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data_3:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus_3.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9092:9090
    networks:
      - back-tier
    depends_on:
      - prometheus_1
      - prometheus_2
    restart: always

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus_1
      - prometheus_2
      - prometheus_3
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always
