global:
  scrape_interval:     1m # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'federate'
    scrape_interval: 1m
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
#        - '{job="example-random"}'
        - '{__name__=~"job:.*"}'
#        - '{job="job:status_application_1:3m"}'
    static_configs:
    - targets:
      - 'prometheus_1:9090'
      - 'prometheus_2:9090'
