global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'
rule_files:
  - rules_1.yml
scrape_configs:
  - job_name: 'status_application_1'
    scrape_interval: 1m
    static_configs:
      - targets: ['192.168.1.28:8000']
